version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yuzu-dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - yuzu-dependency-cache-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yuzu-dependency-cache-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: test
          command: yarn test --browsers ChromeHeadlessCI
          environment:
            CIRCLE_CI: true
